/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedComplianceRouteRouteImport } from './routes/_authenticated/compliance/route'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthenticatedComplianceIndexRouteImport } from './routes/_authenticated/compliance/index'
import { Route as ApiBffSplatRouteImport } from './routes/api/bff/$'
import { Route as AuthenticatedComplianceAuditIndexRouteImport } from './routes/_authenticated/compliance/audit/index'
import { Route as AuthenticatedComplianceClaimsIndexRouteImport } from './routes/_authenticated/compliance/claims/index'
import { Route as AuthenticatedComplianceConsentIndexRouteImport } from './routes/_authenticated/compliance/consent/index'
import { Route as AuthenticatedComplianceControlsIndexRouteImport } from './routes/_authenticated/compliance/controls/index'
import { Route as AuthenticatedComplianceCoursesIndexRouteImport } from './routes/_authenticated/compliance/courses/index'
import { Route as AuthenticatedComplianceDataRequestsIndexRouteImport } from './routes/_authenticated/compliance/data-requests/index'
import { Route as AuthenticatedComplianceEmailsIndexRouteImport } from './routes/_authenticated/compliance/emails/index'
import { Route as AuthenticatedComplianceMinorsIndexRouteImport } from './routes/_authenticated/compliance/minors/index'
import { Route as AuthenticatedCompliancePaymentsIndexRouteImport } from './routes/_authenticated/compliance/payments/index'
import { Route as AuthenticatedComplianceRefundsIndexRouteImport } from './routes/_authenticated/compliance/refunds/index'
import { Route as AuthenticatedComplianceSettingsIndexRouteImport } from './routes/_authenticated/compliance/settings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComplianceRouteRoute =
  AuthenticatedComplianceRouteRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComplianceIndexRoute =
  AuthenticatedComplianceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)
const ApiBffSplatRoute = ApiBffSplatRouteImport.update({
  id: '/api/bff/$',
  path: '/api/bff/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComplianceAuditIndexRoute =
  AuthenticatedComplianceAuditIndexRouteImport.update({
    id: '/audit/',
    path: '/audit/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)
const AuthenticatedComplianceClaimsIndexRoute =
  AuthenticatedComplianceClaimsIndexRouteImport.update({
    id: '/claims/',
    path: '/claims/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)
const AuthenticatedComplianceConsentIndexRoute =
  AuthenticatedComplianceConsentIndexRouteImport.update({
    id: '/consent/',
    path: '/consent/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)
const AuthenticatedComplianceControlsIndexRoute =
  AuthenticatedComplianceControlsIndexRouteImport.update({
    id: '/controls/',
    path: '/controls/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)
const AuthenticatedComplianceCoursesIndexRoute =
  AuthenticatedComplianceCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)
const AuthenticatedComplianceDataRequestsIndexRoute =
  AuthenticatedComplianceDataRequestsIndexRouteImport.update({
    id: '/data-requests/',
    path: '/data-requests/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)
const AuthenticatedComplianceEmailsIndexRoute =
  AuthenticatedComplianceEmailsIndexRouteImport.update({
    id: '/emails/',
    path: '/emails/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)
const AuthenticatedComplianceMinorsIndexRoute =
  AuthenticatedComplianceMinorsIndexRouteImport.update({
    id: '/minors/',
    path: '/minors/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)
const AuthenticatedCompliancePaymentsIndexRoute =
  AuthenticatedCompliancePaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)
const AuthenticatedComplianceRefundsIndexRoute =
  AuthenticatedComplianceRefundsIndexRouteImport.update({
    id: '/refunds/',
    path: '/refunds/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)
const AuthenticatedComplianceSettingsIndexRoute =
  AuthenticatedComplianceSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedComplianceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof AuthenticatedComplianceRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/api/bff/$': typeof ApiBffSplatRoute
  '/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/compliance/audit/': typeof AuthenticatedComplianceAuditIndexRoute
  '/compliance/claims/': typeof AuthenticatedComplianceClaimsIndexRoute
  '/compliance/consent/': typeof AuthenticatedComplianceConsentIndexRoute
  '/compliance/controls/': typeof AuthenticatedComplianceControlsIndexRoute
  '/compliance/courses/': typeof AuthenticatedComplianceCoursesIndexRoute
  '/compliance/data-requests/': typeof AuthenticatedComplianceDataRequestsIndexRoute
  '/compliance/emails/': typeof AuthenticatedComplianceEmailsIndexRoute
  '/compliance/minors/': typeof AuthenticatedComplianceMinorsIndexRoute
  '/compliance/payments/': typeof AuthenticatedCompliancePaymentsIndexRoute
  '/compliance/refunds/': typeof AuthenticatedComplianceRefundsIndexRoute
  '/compliance/settings/': typeof AuthenticatedComplianceSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signin': typeof AuthSigninRoute
  '/api/bff/$': typeof ApiBffSplatRoute
  '/compliance': typeof AuthenticatedComplianceIndexRoute
  '/compliance/audit': typeof AuthenticatedComplianceAuditIndexRoute
  '/compliance/claims': typeof AuthenticatedComplianceClaimsIndexRoute
  '/compliance/consent': typeof AuthenticatedComplianceConsentIndexRoute
  '/compliance/controls': typeof AuthenticatedComplianceControlsIndexRoute
  '/compliance/courses': typeof AuthenticatedComplianceCoursesIndexRoute
  '/compliance/data-requests': typeof AuthenticatedComplianceDataRequestsIndexRoute
  '/compliance/emails': typeof AuthenticatedComplianceEmailsIndexRoute
  '/compliance/minors': typeof AuthenticatedComplianceMinorsIndexRoute
  '/compliance/payments': typeof AuthenticatedCompliancePaymentsIndexRoute
  '/compliance/refunds': typeof AuthenticatedComplianceRefundsIndexRoute
  '/compliance/settings': typeof AuthenticatedComplianceSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/compliance': typeof AuthenticatedComplianceRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/api/bff/$': typeof ApiBffSplatRoute
  '/_authenticated/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/_authenticated/compliance/audit/': typeof AuthenticatedComplianceAuditIndexRoute
  '/_authenticated/compliance/claims/': typeof AuthenticatedComplianceClaimsIndexRoute
  '/_authenticated/compliance/consent/': typeof AuthenticatedComplianceConsentIndexRoute
  '/_authenticated/compliance/controls/': typeof AuthenticatedComplianceControlsIndexRoute
  '/_authenticated/compliance/courses/': typeof AuthenticatedComplianceCoursesIndexRoute
  '/_authenticated/compliance/data-requests/': typeof AuthenticatedComplianceDataRequestsIndexRoute
  '/_authenticated/compliance/emails/': typeof AuthenticatedComplianceEmailsIndexRoute
  '/_authenticated/compliance/minors/': typeof AuthenticatedComplianceMinorsIndexRoute
  '/_authenticated/compliance/payments/': typeof AuthenticatedCompliancePaymentsIndexRoute
  '/_authenticated/compliance/refunds/': typeof AuthenticatedComplianceRefundsIndexRoute
  '/_authenticated/compliance/settings/': typeof AuthenticatedComplianceSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/auth/signin'
    | '/api/bff/$'
    | '/compliance/'
    | '/compliance/audit/'
    | '/compliance/claims/'
    | '/compliance/consent/'
    | '/compliance/controls/'
    | '/compliance/courses/'
    | '/compliance/data-requests/'
    | '/compliance/emails/'
    | '/compliance/minors/'
    | '/compliance/payments/'
    | '/compliance/refunds/'
    | '/compliance/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signin'
    | '/api/bff/$'
    | '/compliance'
    | '/compliance/audit'
    | '/compliance/claims'
    | '/compliance/consent'
    | '/compliance/controls'
    | '/compliance/courses'
    | '/compliance/data-requests'
    | '/compliance/emails'
    | '/compliance/minors'
    | '/compliance/payments'
    | '/compliance/refunds'
    | '/compliance/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/compliance'
    | '/auth/signin'
    | '/api/bff/$'
    | '/_authenticated/compliance/'
    | '/_authenticated/compliance/audit/'
    | '/_authenticated/compliance/claims/'
    | '/_authenticated/compliance/consent/'
    | '/_authenticated/compliance/controls/'
    | '/_authenticated/compliance/courses/'
    | '/_authenticated/compliance/data-requests/'
    | '/_authenticated/compliance/emails/'
    | '/_authenticated/compliance/minors/'
    | '/_authenticated/compliance/payments/'
    | '/_authenticated/compliance/refunds/'
    | '/_authenticated/compliance/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  ApiBffSplatRoute: typeof ApiBffSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compliance/': {
      id: '/_authenticated/compliance/'
      path: '/'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AuthenticatedComplianceIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
    '/api/bff/$': {
      id: '/api/bff/$'
      path: '/api/bff/$'
      fullPath: '/api/bff/$'
      preLoaderRoute: typeof ApiBffSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compliance/audit/': {
      id: '/_authenticated/compliance/audit/'
      path: '/audit'
      fullPath: '/compliance/audit/'
      preLoaderRoute: typeof AuthenticatedComplianceAuditIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
    '/_authenticated/compliance/claims/': {
      id: '/_authenticated/compliance/claims/'
      path: '/claims'
      fullPath: '/compliance/claims/'
      preLoaderRoute: typeof AuthenticatedComplianceClaimsIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
    '/_authenticated/compliance/consent/': {
      id: '/_authenticated/compliance/consent/'
      path: '/consent'
      fullPath: '/compliance/consent/'
      preLoaderRoute: typeof AuthenticatedComplianceConsentIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
    '/_authenticated/compliance/controls/': {
      id: '/_authenticated/compliance/controls/'
      path: '/controls'
      fullPath: '/compliance/controls/'
      preLoaderRoute: typeof AuthenticatedComplianceControlsIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
    '/_authenticated/compliance/courses/': {
      id: '/_authenticated/compliance/courses/'
      path: '/courses'
      fullPath: '/compliance/courses/'
      preLoaderRoute: typeof AuthenticatedComplianceCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
    '/_authenticated/compliance/data-requests/': {
      id: '/_authenticated/compliance/data-requests/'
      path: '/data-requests'
      fullPath: '/compliance/data-requests/'
      preLoaderRoute: typeof AuthenticatedComplianceDataRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
    '/_authenticated/compliance/emails/': {
      id: '/_authenticated/compliance/emails/'
      path: '/emails'
      fullPath: '/compliance/emails/'
      preLoaderRoute: typeof AuthenticatedComplianceEmailsIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
    '/_authenticated/compliance/minors/': {
      id: '/_authenticated/compliance/minors/'
      path: '/minors'
      fullPath: '/compliance/minors/'
      preLoaderRoute: typeof AuthenticatedComplianceMinorsIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
    '/_authenticated/compliance/payments/': {
      id: '/_authenticated/compliance/payments/'
      path: '/payments'
      fullPath: '/compliance/payments/'
      preLoaderRoute: typeof AuthenticatedCompliancePaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
    '/_authenticated/compliance/refunds/': {
      id: '/_authenticated/compliance/refunds/'
      path: '/refunds'
      fullPath: '/compliance/refunds/'
      preLoaderRoute: typeof AuthenticatedComplianceRefundsIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
    '/_authenticated/compliance/settings/': {
      id: '/_authenticated/compliance/settings/'
      path: '/settings'
      fullPath: '/compliance/settings/'
      preLoaderRoute: typeof AuthenticatedComplianceSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedComplianceRouteRoute
    }
  }
}

interface AuthenticatedComplianceRouteRouteChildren {
  AuthenticatedComplianceIndexRoute: typeof AuthenticatedComplianceIndexRoute
  AuthenticatedComplianceAuditIndexRoute: typeof AuthenticatedComplianceAuditIndexRoute
  AuthenticatedComplianceClaimsIndexRoute: typeof AuthenticatedComplianceClaimsIndexRoute
  AuthenticatedComplianceConsentIndexRoute: typeof AuthenticatedComplianceConsentIndexRoute
  AuthenticatedComplianceControlsIndexRoute: typeof AuthenticatedComplianceControlsIndexRoute
  AuthenticatedComplianceCoursesIndexRoute: typeof AuthenticatedComplianceCoursesIndexRoute
  AuthenticatedComplianceDataRequestsIndexRoute: typeof AuthenticatedComplianceDataRequestsIndexRoute
  AuthenticatedComplianceEmailsIndexRoute: typeof AuthenticatedComplianceEmailsIndexRoute
  AuthenticatedComplianceMinorsIndexRoute: typeof AuthenticatedComplianceMinorsIndexRoute
  AuthenticatedCompliancePaymentsIndexRoute: typeof AuthenticatedCompliancePaymentsIndexRoute
  AuthenticatedComplianceRefundsIndexRoute: typeof AuthenticatedComplianceRefundsIndexRoute
  AuthenticatedComplianceSettingsIndexRoute: typeof AuthenticatedComplianceSettingsIndexRoute
}

const AuthenticatedComplianceRouteRouteChildren: AuthenticatedComplianceRouteRouteChildren =
  {
    AuthenticatedComplianceIndexRoute: AuthenticatedComplianceIndexRoute,
    AuthenticatedComplianceAuditIndexRoute:
      AuthenticatedComplianceAuditIndexRoute,
    AuthenticatedComplianceClaimsIndexRoute:
      AuthenticatedComplianceClaimsIndexRoute,
    AuthenticatedComplianceConsentIndexRoute:
      AuthenticatedComplianceConsentIndexRoute,
    AuthenticatedComplianceControlsIndexRoute:
      AuthenticatedComplianceControlsIndexRoute,
    AuthenticatedComplianceCoursesIndexRoute:
      AuthenticatedComplianceCoursesIndexRoute,
    AuthenticatedComplianceDataRequestsIndexRoute:
      AuthenticatedComplianceDataRequestsIndexRoute,
    AuthenticatedComplianceEmailsIndexRoute:
      AuthenticatedComplianceEmailsIndexRoute,
    AuthenticatedComplianceMinorsIndexRoute:
      AuthenticatedComplianceMinorsIndexRoute,
    AuthenticatedCompliancePaymentsIndexRoute:
      AuthenticatedCompliancePaymentsIndexRoute,
    AuthenticatedComplianceRefundsIndexRoute:
      AuthenticatedComplianceRefundsIndexRoute,
    AuthenticatedComplianceSettingsIndexRoute:
      AuthenticatedComplianceSettingsIndexRoute,
  }

const AuthenticatedComplianceRouteRouteWithChildren =
  AuthenticatedComplianceRouteRoute._addFileChildren(
    AuthenticatedComplianceRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedComplianceRouteRoute: typeof AuthenticatedComplianceRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedComplianceRouteRoute:
    AuthenticatedComplianceRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  ApiBffSplatRoute: ApiBffSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
